name: Test all platforms

on: [ push, pull_request ]

jobs:
  test-linux:
    uses: ./.github/workflows/test.yml

  test-macos:
    uses: ./.github/workflows/test.yml
    with:
      os: macos

  test-windows:
    uses: ./.github/workflows/test.yml
    with:
      os: windows

  coveralls:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [test-linux, test-macos, test-windows]
    env:
      COVERALLS_SERVICE_NUMBER: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
    steps:
    - uses: coverallsapp/github-action@v2
      with:
        carryforward: "all"
        parallel-finished: true
