name: Test all platforms

on: [ push, pull_request ]

jobs:
  test-linux:
    uses: ./.github/workflows/test.yml
    secrets:
      token: ${{ secrets.COVERALLS_REPO_TOKEN }}

  test-macos:
    uses: ./.github/workflows/test.yml
    with:
      os: macos
    secrets:
      token: ${{ secrets.COVERALLS_REPO_TOKEN }}

  test-windows:
    uses: ./.github/workflows/test.yml
    with:
      os: windows
    secrets:
      token: ${{ secrets.COVERALLS_REPO_TOKEN }}

  coveralls:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [test-linux, test-macos, test-windows]
    steps:
    - uses: coverallsapp/github-action@v2
      with:
        carryforward: "linux-1,linux-2,macos-2,macos-2,windows-1,windows-1"
        parallel-finished: true
