name: Test (macOS)

on: [ push, pull_request ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        test_number: [ 1, 2 ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: npm
    - run: npm ci
    - run: npm test -- test/run${{ matrix.test_number }}.js
    - name: Coveralls
      uses: coverallsapp/github-action@v1
      env:
        COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
      with:
        parallel: true
        flag-name: macos-${{ matrix.test_number }}
        debug: true
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-data-macos-${{ matrix.test_number }}
        path: coverage/

