name: Reusable test workflow
run-name: Run tests on ${{ inputs.os }}

on:
  workflow_call:
    inputs:
      build_id:
        type: string
        default: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
        description: |
          Build identifier for the current run. This is sent as `service_number` to Coveralls.
      os:
        type: string
        default: ubuntu
        description: |
          The type of machine to run the job on. Can be one of 'ubuntu' (default), 'macos', or 'windows'.
      upload_coverage:
        type: boolean
        default: true
        description: |
          Whether to upload the coverage data to Coveralls.
      store_coverage:
        type: boolean
        default: true
        description: |
          Whether to store the coverage data as an artifact.
    secrets:
      token:
        required: true

env:
  COVERALLS_SERVICE_NUMBER: ${{ inputs.build_id }}
  COVERALLS_REPO_TOKEN: ${{ secrets.token }}

jobs:
  test:
    runs-on: ${{ inputs.os }}-latest
    strategy:
      matrix:
        test_number: [ 1, 2 ]
    outputs:
      build_id: ${{ inputs.build_id }}
      result: ${{ steps.coveralls.outputs.coveralls-api-result}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: npm
    - run: npm ci
    - run: npm test -- test/run${{ matrix.test_number }}.js
    - name: Coveralls
      id: coveralls
      if: ${{ inputs.upload_coverage }}
      uses: mrexox/coveralls-github-action@feat/use-pwsh-for-windows
      with:
        parallel: true
        flag-name: ${{ inputs.os }}-${{ matrix.test_number }}
        debug: true
    - uses: actions/upload-artifact@v3
      if: ${{ inputs.store_coverage }}
      with:
        name: coverage-data-${{ inputs.os }}-${{ matrix.test_number }}
        path: coverage/
